### ISSUE TITLE
Error marker on HenshinResourceSet even though its fine.

### ISSUE THREAD

**Issue by KristopherBorn** [leodejevga/Model-Testing#2]
In the bank example an error marker denotes the HenshinResourceSet with "Path Error: Resourceset Not  initialized"
Nevertheless the HenshinResourceSet is initilized correctly.

![image](https://cloud.githubusercontent.com/assets/19552622/22728505/97ecba2a-edde-11e6-8964-41c249bd48c7.png)

**Comment by leodejevga** [comment]
Regex Expression was incorrect.
Solved
