### ISSUE TITLE
underlining the erroneous part in the editor required

### ISSUE THREAD

**Issue by KristopherBorn** [leodejevga/Model-Testing#6]
Underlining the erroneous part in the editor required.
expected outcome:
![underlining](https://cloud.githubusercontent.com/assets/19552622/23018271/af57292e-f43d-11e6-988c-721a634a8b2b.jpg)

hints can be found on:
http://cubussapiens.hu/2010/11/markers-and-annotations-in-eclipse-for-error-feedback/

most likely the org.eclipse.core.resources.IMarker API supports this by the following snippet:
`if (pos.offset != 0) {
  marker.setAttribute(IMarker.CHAR_START,pos.offset);
  marker.setAttribute(IMarker.CHAR_END,pos.offset+pos.length);
}`

In current implementation this seems to be related with the `private void addMarker(IFile file, String message, int lineNumber,int severity)` method in the Builder.java

**Comment by leodejevga** [comment]
Fertig gestellt
